force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <description>Holds car details.</description>
    <label>Car</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Car</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>S</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Car__c/fields/Cost_Template__c.field-meta.xml
<CustomField>
    <fullName>Cost_Template__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup field to Upgrade template.</description>
    <inlineHelpText>Lookup field to Upgrade template.</inlineHelpText>
    <label>Cost Template</label>
    <referenceTo>Upgrade_Template__c</referenceTo>
    <relationshipLabel>Car</relationshipLabel>
    <relationshipName>Car</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Image_Url__c.field-meta.xml
<CustomField>
    <fullName>Image_Url__c</fullName>
    <label>Image URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Max_Stars__c.field-meta.xml
<CustomField>
    <fullName>Max_Stars__c</fullName>
    <label>Max Stars</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Rarity__c.field-meta.xml
<CustomField>
    <fullName>Rarity__c</fullName>
    <label>Rarity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Epic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Car__c/fields/Release_Date__c.field-meta.xml
<CustomField>
    <fullName>Release_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Release Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Unlock_Type__c.field-meta.xml
<CustomField>
    <fullName>Unlock_Type__c</fullName>
    <label>Unlock Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Blueprints</fullName>
                <default>true</default>
                <label>Blueprints</label>
            </value>
            <value>
                <fullName>Key</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Car_Star_Level__c/Car_Star_Level__c.object-meta.xml
<CustomObject>
    <description>Holds star and stage information for each car.</description>
    <label>Car Star Level</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Car Star Levels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Car_Star_Level__c/fields/Accel_Max__c.field-meta.xml
<CustomField>
    <fullName>Accel_Max__c</fullName>
    <label>Accel Max</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Car_Star_Level__c/fields/Blueprints_Required__c.field-meta.xml
<CustomField>
    <fullName>Blueprints_Required__c</fullName>
    <label>Blueprints Required</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Car_Star_Level__c/fields/Car__c.field-meta.xml
<CustomField>
    <fullName>Car__c</fullName>
    <description>Holds car data.</description>
    <inlineHelpText>Holds car data.</inlineHelpText>
    <label>Car</label>
    <referenceTo>Car__c</referenceTo>
    <relationshipLabel>Car Star Levels</relationshipLabel>
    <relationshipName>Car_Star_Levels</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Car_Star_Level__c/fields/Handling_Max__c.field-meta.xml
<CustomField>
    <fullName>Handling_Max__c</fullName>
    <label>Handling Max</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Car_Star_Level__c/fields/Nitro_Max__c.field-meta.xml
<CustomField>
    <fullName>Nitro_Max__c</fullName>
    <label>Nitro Max</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Car_Star_Level__c/fields/Rank_Max__c.field-meta.xml
<CustomField>
    <fullName>Rank_Max__c</fullName>
    <label>Rank Max</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Car_Star_Level__c/fields/Rank_Min__c.field-meta.xml
<CustomField>
    <fullName>Rank_Min__c</fullName>
    <label>Rank Min</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Car_Star_Level__c/fields/Star_Level__c.field-meta.xml
<CustomField>
    <fullName>Star_Level__c</fullName>
    <label>Star Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Car_Star_Level__c/fields/Top_Speed_Max__c.field-meta.xml
<CustomField>
    <fullName>Top_Speed_Max__c</fullName>
    <label>Top Speed Max</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Upgrade_Template__c/Upgrade_Template__c.object-meta.xml
<CustomObject>
    <description>Cost template for different class types of car.</description>
    <label>Upgrade Template</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Upgrade Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CarDataController.cls
public with sharing class CarDataController {
  @AuraEnabled(cacheable=true)
  public static List<Car__c> getCarList() {
    return [
      SELECT
        Id,
        Name,
        Class__c,
        Rarity__c,
        Max_Stars__c,
        (SELECT Id FROM Car_Star_Levels__r)
      FROM Car__c
      WITH SECURITY_ENFORCED
      ORDER BY Name ASC
    ];
  }

  @AuraEnabled(cacheable=true)
  public static Car__c getCarDetail(Id carId) {
    return [
      SELECT
        Id,
        Name,
        Class__c,
        Rarity__c,
        Max_Stars__c,
        Release_Date__c,
        Unlock_Type__c,
        Image_Url__c,
        Cost_Template__r.Name,
        (
          SELECT
            Id,
            Star_Level__c,
            Blueprints_Required__c,
            Rank_Min__c,
            Rank_Max__c,
            Top_Speed_Max__c,
            Accel_Max__c,
            Handling_Max__c,
            Nitro_Max__c
          FROM Car_Star_Levels__r
          ORDER BY Star_Level__c ASC
        )
      FROM Car__c
      WHERE Id = :carId
      WITH SECURITY_ENFORCED
    ];
  }
}